apiVersion: batch/v1
kind: Job
metadata:
  name: sysbench-job
  labels:
    app: sysbench
spec:
  parallelism: 1
    # selector:
    #   matchLabels:
    #     app: sysbench
  template:
    metadata:
      annotations:
        blockio.kubernetes.io/container.stress.rbps: '0M/4k'
        blockio.kubernetes.io/container.stress.wbps: '2M/4k'
      labels:
        app: sysbench
    spec:
      restartPolicy: Never
      containers:
      - name: sysbench
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        image: openebs/sysbench-client
        command:
        - sh
        - -c
        - "sysbench /usr/share/sysbench/oltp_write_only.lua --tables=2 --table_size=2  --mysql-user=root --mysql-password=123456 --mysql-host=mysql-rocksdb.default.svc.cluster.local --mysql-port=3306 --mysql-db=rocks_demo --threads=20  --time=300 --report-interval=3 cleanup;
          sysbench /usr/share/sysbench/oltp_write_only.lua --tables=2 --table_size=2  --mysql-user=root --mysql-password=123456 --mysql-host=mysql-rocksdb.default.svc.cluster.local --mysql-port=3306 --mysql-db=rocks_demo --threads=20  --time=300 --report-interval=3 prepare;
          sysbench /usr/share/sysbench/oltp_write_only.lua --tables=2 --table_size=5000000  --mysql-user=root --mysql-password=123456 --mysql-host=mysql-rocksdb.default.svc.cluster.local --mysql-port=3306 --mysql-db=rocks_demo --threads=20  --time=3600 --report-interval=3 run"
      nodeSelector:
        kubernetes.io/hostname: ioi-1
